version: "3.9"

networks:
  myst-movie:
    driver: bridge

services:
  app:
    container_name: movie-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    networks:
      - myst-movie
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: MystMovie
    ports:
      - "5432:5432"
    networks:
      - myst-movie
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
